sources:
  - name: source
    database: '{{ target.database }}'
    schema: source  
    tables:
      - name: dim_customer
      - name: dim_product
      - name: dim_store
      - name: dim_date
      - name: fact_return
      - name: fact_sales
      - name : items
