name: DBT CI

on:
  push:
    branches:
      - main

jobs:
  dbt:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt
        run: |
          pip install -r requirements-ci.txt

      - name: Check dbt version
        run: dbt --version

      - name: Test Snowflake connection
        working-directory: dbt_yt_tutorial
        run: |
          dbt debug \
            --target prod \
            --profiles-dir ../.github/dbt